// ================================= DOCUMENTATION ------------------------------------------
// Script: BoletimDiario V3
// Purpose: Dashboard gerencial diário dos equipamentos do COA Center.
// ==========================================================================================

import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { supabase } from '../../../lib/supabaseClient';
import BoletimDiarioModal from './BoletimDiarioModal';
import './BoletimDiario.css';

const DEFAULT_CATEGORIES = ['AGRÍCOLA', 'APOIO'];
const PAGE_SIZE = 1000;
const QUERY_RETRIES = 2;
const RETRY_DELAY_MS = 1200;
const DATA_CACHE = new Map();
const OPERATIONS_CACHE = new Map();

const DASH_CONFIG = {
  tooltipWidth: 330,
  tooltipHeight: 220,
  tooltipTitlePx: 14,
  tooltipTextPx: 11,
  tooltipValuePx: 12,
};

const KPI_CONFIG = [
  { key: 'eficiencia_operacional', label: 'Ef. Operacional', short: 'EF', inverse: false },
  { key: 'eficiencia_real', label: 'Ef. Real', short: 'ER', inverse: false },
  { key: 'sem_apontamento', label: 'S. Apontamento', short: 'S.AP', inverse: true },
  { key: 'indeterminado', label: 'Indeterminado', short: 'IND', inverse: true },
  { key: 'disponibilidade_mecanica', label: 'Disp. Mecânica', short: 'DM', inverse: false },
  { key: 'motor_ocioso', label: 'Motor Ocioso', short: 'OC', inverse: true },
];

const EQUIPMENT_TAGS = KPI_CONFIG.filter(({ key }) => ['eficiencia_operacional','sem_apontamento','indeterminado','disponibilidade_mecanica','motor_ocioso'].includes(key));
const SECOND_FIELDS = ['produtivo_seg','improdutivo_seg','auxiliar_seg','s_apont_seg','indeter_seg','manutencao_seg','clima_seg','fabrica_parada_seg','sem_turno_seg','hrs_operacionais_seg','hrs_disp_seg','hrs_motor_ligado_seg','hrs_ocioso_seg'];
const OPERATION_GROUPS = [
  { key:'produtivo_seg',label:'Produtivo',color:'#3ddc97' },
  { key:'improdutivo_seg',label:'Improdutivo',color:'#b3c0d0' },
  { key:'auxiliar_seg',label:'Auxiliar',color:'#a8b6c8' },
  { key:'s_apont_seg',label:'Sem apontamento',color:'#f59e0b' },
  { key:'indeter_seg',label:'Indeterminado',color:'#f59e0b' },
  { key:'manutencao_seg',label:'Manutenção',color:'#a78bfa' },
  { key:'clima_seg',label:'Clima',color:'#7f91a7' },
  { key:'fabrica_parada_seg',label:'Fábrica parada',color:'#74879f' },
  { key:'sem_turno_seg',label:'Sem turno',color:'#697d96' },
];

const num=(value,fallback=0)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback;};
const normalizeRows=(rows)=>(Array.isArray(rows)?rows:[]).map((row)=>{const normalized={...row};SECOND_FIELDS.forEach((field)=>{normalized[field]=num(row[field]);});KPI_CONFIG.forEach(({key})=>{normalized[key]=row[key]==null?null:num(row[key]);});return normalized;});
const sumRows=(rows)=>rows.reduce((acc,row)=>{SECOND_FIELDS.forEach((field)=>{acc[field]+=num(row[field]);});return acc;},Object.fromEntries(SECOND_FIELDS.map((field)=>[field,0])));
const safePercent=(numerator,denominator)=>denominator>0?(numerator/denominator)*100:null;
const calculateIndicators=(totals)=>({eficiencia_operacional:safePercent(totals.produtivo_seg,totals.hrs_disp_seg),eficiencia_real:safePercent(totals.produtivo_seg,totals.hrs_operacionais_seg),sem_apontamento:safePercent(totals.s_apont_seg,totals.hrs_operacionais_seg),indeterminado:safePercent(totals.indeter_seg,totals.hrs_operacionais_seg),disponibilidade_mecanica:totals.hrs_operacionais_seg>0?(1-totals.manutencao_seg/totals.hrs_operacionais_seg)*100:null,motor_ocioso:safePercent(totals.hrs_ocioso_seg,totals.hrs_operacionais_seg)});
const formatPercent=(value,decimals=1)=>value==null||!Number.isFinite(value)?'—':`${value.toFixed(decimals).replace('.',',')}%`;
const formatDuration=(seconds)=>{const totalMinutes=Math.max(0,Math.round(num(seconds)/60));const hours=Math.floor(totalMinutes/60);const minutes=totalMinutes%60;return `${hours.toLocaleString('pt-BR',{minimumIntegerDigits:2,useGrouping:true})}:${String(minutes).padStart(2,'0')}`;};
const formatDate=(isoDate)=>{if(!isoDate)return'—';const[year,month,day]=isoDate.slice(0,10).split('-');return`${day}/${month}/${year}`;};
const MONTHS_SHORT=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];
const formatDateShort=(isoDate)=>{if(!isoDate)return'—';const[,month,day]=isoDate.slice(0,10).split('-');return`${day}-${MONTHS_SHORT[Number(month)-1]||month}`;};
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const fetchAllPages=async(queryFactory)=>{const allRows=[];for(let from=0;;from+=PAGE_SIZE){let page=[];let lastError=null;for(let attempt=0;attempt<=QUERY_RETRIES;attempt+=1){const{data,error}=await queryFactory().range(from,from+PAGE_SIZE-1);if(!error){page=Array.isArray(data)?data:[];lastError=null;break;}lastError=error;if(attempt<QUERY_RETRIES)await sleep(RETRY_DELAY_MS*(attempt+1));}if(lastError)throw lastError;allRows.push(...page);if(page.length<PAGE_SIZE)break;}return allRows;};
const kpiTone=(key,value)=>{if(value==null)return'neutral';if(key==='eficiencia_real')return'reference';if(key==='eficiencia_operacional')return value>=65?'good':value>=50?'warning':'bad';if(key==='disponibilidade_mecanica')return value>=90?'good':value>=80?'warning':'bad';if(key==='sem_apontamento')return value<=2?'good':'bad';if(key==='indeterminado')return value<=10?'good':'bad';if(key==='motor_ocioso')return value<=5?'good':'bad';return'neutral';};

function DashboardTooltip({tooltip}){
  if(!tooltip||typeof document==='undefined')return null;
  const{config,history=[],currentValue,position}=tooltip;const valid=history.filter((item)=>item?.value!=null&&Number.isFinite(item.value));const values=valid.map((item)=>item.value);const average=values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;const delta=average==null||currentValue==null?null:currentValue-average;const better=delta==null?null:config.inverse?delta<=0:delta>=0;const width=290,height=92,padX=18,padTop=25,padBottom=13,min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1,range=Math.max(.01,max-min);const points=valid.map((item,index)=>({...item,x:padX+index*((width-padX*2)/Math.max(1,valid.length-1)),y:padTop+((max-item.value)/range)*(height-padTop-padBottom),tone:kpiTone(config.key,item.value)}));
  return createPortal(<div className="bd-kpi-floating-tooltip bd-dashboard-tooltip" style={{left:position.left,top:position.top,width:DASH_CONFIG.tooltipWidth,minHeight:DASH_CONFIG.tooltipHeight,'--tooltip-title-px':`${DASH_CONFIG.tooltipTitlePx}px`,'--tooltip-text-px':`${DASH_CONFIG.tooltipTextPx}px`,'--tooltip-value-px':`${DASH_CONFIG.tooltipValuePx}px`}}><div className="bd-kpi-floating-tooltip__head"><strong>Histórico {config.label}</strong></div><svg className="bd-kpi-tooltip-line" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><line x1={padX} x2={width-padX} y1={height-padBottom} y2={height-padBottom}/><polyline points={points.map((item)=>`${item.x},${item.y}`).join(' ')}/>{points.map((item)=><g key={item.data}><circle cx={item.x} cy={item.y} r="3.5" className={`is-${item.tone}`}/><text x={item.x} y={Math.max(10,item.y-8)} textAnchor="middle" className={`is-${item.tone}`}>{formatPercent(item.value)}</text></g>)}</svg><div className="bd-kpi-tooltip-dates">{points.map((item)=><span key={item.data}>{formatDateShort(item.data)}</span>)}</div><div className="bd-kpi-tooltip-comparison"><span>Média <b className={`is-${kpiTone(config.key,average)}`}>{formatPercent(average)}</b></span><strong className={better===false?'is-bad':better===null?'is-reference':'is-good'}>{delta==null?'—':`${delta>=0?'+':''}${delta.toFixed(1).replace('.',',')} p.p.`}</strong></div></div>,document.body);
}

function Sparkline({values,currentValue,inverse}){const valid=values.map((item)=>typeof item==='object'?item.value:item).filter((value)=>value!=null&&Number.isFinite(value));const width=180,height=44,padding=4,min=Math.min(...valid,0),max=Math.max(...valid,1),range=Math.max(1,max-min),points=valid.map((value,index)=>`${padding+index*((width-padding*2)/Math.max(1,valid.length-1))},${height-padding-((value-min)/range)*(height-padding*2)}`).join(' '),average=valid.length?valid.reduce((sum,value)=>sum+value,0)/valid.length:null,delta=average==null||currentValue==null?null:currentValue-average,better=delta==null?null:inverse?delta<=0:delta>=0;return <div className="bd-sparkline"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><polyline points={points} className={better===false?'is-bad':better===null?'is-reference':'is-good'}/></svg><div className="bd-comparison"><span>Média 7d <b>{formatPercent(average)}</b></span><strong className={better===false?'is-bad':better===null?'is-reference':'is-good'}>{delta==null?'—':`${delta>=0?'+':''}${delta.toFixed(1).replace('.',',')} p.p.`}</strong></div></div>;}
function KpiCard({config,value,history,onTooltip,onTooltipClose}){return <article className={`bd-kpi-card is-${kpiTone(config.key,value)}`} onMouseEnter={(event)=>onTooltip(event,config,history,value)} onMouseLeave={onTooltipClose}><div className="bd-kpi-card__top"><span>{config.label}</span><i/></div><strong>{formatPercent(value)}</strong><Sparkline values={history} currentValue={value} inverse={config.inverse}/></article>;}

function CalendarModal({dates,selectedDate,onSelect,onClose}){const selected=dates.find((item)=>item.data===selectedDate)||dates[0];const[year,setYear]=useState(selected?.ano||new Date().getFullYear());const[month,setMonth]=useState(selected?.mes||new Date().getMonth()+1);const dateMap=useMemo(()=>new Map(dates.map((item)=>[item.data,item])),[dates]);const firstDay=new Date(year,month-1,1).getDay(),daysInMonth=new Date(year,month,0).getDate(),months=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'],years=[...new Set(dates.map((item)=>item.ano))].sort((a,b)=>b-a);return <div className="bd-calendar-backdrop" onMouseDown={onClose}><div className="bd-calendar" onMouseDown={(event)=>event.stopPropagation()}><header><div><span className="bd-overline">Data operacional</span><h3>Selecionar data</h3></div><button type="button" onClick={onClose}>×</button></header><div className="bd-calendar__controls"><select value={month} onChange={(event)=>setMonth(Number(event.target.value))}>{months.map((name,index)=><option key={name} value={index+1}>{name}</option>)}</select><select value={year} onChange={(event)=>setYear(Number(event.target.value))}>{years.map((item)=><option key={item}>{item}</option>)}</select></div><div className="bd-calendar__grid">{['D','S','T','Q','Q','S','S'].map((day,index)=><b key={`${day}-${index}`}>{day}</b>)}{Array.from({length:firstDay}).map((_,index)=><span key={`empty-${index}`}/>)}{Array.from({length:daysInMonth},(_,index)=>{const day=index+1,iso=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,available=dateMap.has(iso);return <button key={iso} type="button" disabled={!available} className={selectedDate===iso?'is-active':''} onClick={()=>{onSelect(iso);onClose();}}>{day}</button>;})}</div></div></div>;}

function FilterModal({areaOptions,frontOptions,selectedAreas,selectedFronts,onApply,onClose}){
  const[draftAreas,setDraftAreas]=useState(selectedAreas);const[draftFronts,setDraftFronts]=useState(selectedFronts);
  const availableArea=(name)=>!draftFronts.length||areaOptions.some((item)=>item.name===name&&item.fronts.some((front)=>draftFronts.includes(front)));
  const availableFront=(name)=>!draftAreas.length||frontOptions.some((item)=>item.name===name&&item.areas.some((area)=>draftAreas.includes(area)));
  const toggle=(setter,value)=>setter((previous)=>previous.includes(value)?previous.filter((item)=>item!==value):[...previous,value]);
  const areaText=draftAreas.length?draftAreas.join(', '):'todas as áreas';const frontText=draftFronts.length?draftFronts.join(', '):'';
  return <div className="bd-filter-modal-backdrop" onMouseDown={onClose}><div className="bd-filter-modal" onMouseDown={(event)=>event.stopPropagation()}><header><div><span className="bd-overline">Filtros operacionais</span><h3>Áreas e Frentes</h3></div><button type="button" onClick={onClose}>×</button></header><main><section><div className="bd-filter-modal__title"><strong>Áreas</strong><span>{draftAreas.length||'Todas'}</span></div><div className="bd-filter-modal__grid">{areaOptions.map((item)=><button key={item.name} type="button" disabled={!availableArea(item.name)} className={draftAreas.includes(item.name)?'is-active':''} onClick={()=>toggle(setDraftAreas,item.name)}><span>{item.name}</span><b>{item.count}</b></button>)}</div></section><section><div className="bd-filter-modal__title"><strong>Frentes</strong><span>{draftFronts.length||'Todas'}</span></div><div className="bd-filter-modal__grid">{frontOptions.map((item)=><button key={item.name} type="button" disabled={!availableFront(item.name)} className={draftFronts.includes(item.name)?'is-active':''} onClick={()=>toggle(setDraftFronts,item.name)}><span>{item.name}</span><b>{item.count}</b></button>)}</div></section></main><footer><p>{frontText?`Filtrar frentes ${frontText} de ${areaText}`:`Filtrar ${areaText}`}</p><div><button type="button" className="is-clear" onClick={()=>{setDraftAreas([]);setDraftFronts([]);}}>Limpar</button><button type="button" className="is-confirm" onClick={()=>{onApply(draftAreas,draftFronts);onClose();}}>Confirmar filtros</button></div></footer></div></div>;
}

function FilterRail({categories,activeCategories,onToggleCategory,selectedAreas,selectedFronts,onOpenFilter,search,onSearch}){return <aside className="bd-filter-rail"><section><span className="bd-overline">Categorias</span><div className="bd-category-list">{categories.map((category)=><button key={category} type="button" className={activeCategories.includes(category)?'is-active':''} onClick={()=>onToggleCategory(category)}><span/>{category}</button>)}</div></section><section className="bd-filter-trigger-wrap"><button type="button" className="bd-filter-trigger" onClick={onOpenFilter}><span><b>Filtrar Área</b><small>{selectedAreas.length?`${selectedAreas.length} área(s)`: 'Todas as áreas'}</small></span><i>{selectedAreas.length+selectedFronts.length||'+'}</i></button>{selectedFronts.length>0&&<div className="bd-active-filter-summary">{selectedFronts.slice(0,3).map((front)=><span key={front}>{front}</span>)}{selectedFronts.length>3&&<span>+{selectedFronts.length-3}</span>}</div>}</section><section className="bd-filter-fields"><label><span>Equipamento</span><div className="bd-search-input"><input value={search} onChange={(event)=>onSearch(event.target.value)} placeholder="Buscar código..."/>{search&&<button type="button" onClick={()=>onSearch('')}>×</button>}</div></label></section></aside>;}

function EquipmentTree({rows,onOpenEquipment,search}){const[openAreas,setOpenAreas]=useState(new Set()),[openFronts,setOpenFronts]=useState(new Set());const tree=useMemo(()=>{const areas=new Map();rows.forEach((row)=>{if(!areas.has(row.desc_area))areas.set(row.desc_area,new Map());const fronts=areas.get(row.desc_area);if(!fronts.has(row.desc_grupo))fronts.set(row.desc_grupo,new Map());const equipments=fronts.get(row.desc_grupo);if(!equipments.has(row.cod_equip))equipments.set(row.cod_equip,[]);equipments.get(row.cod_equip).push(row);});return areas;},[rows]);useEffect(()=>{if(search.trim()){setOpenAreas(new Set([...tree.keys()]));setOpenFronts(new Set([...tree.entries()].flatMap(([area,fronts])=>[...fronts.keys()].map((front)=>`${area}|${front}`))));}else{setOpenAreas(new Set());setOpenFronts(new Set());}},[search]);const toggle=(setter,key)=>setter((previous)=>{const next=new Set(previous);next.has(key)?next.delete(key):next.add(key);return next;});return <div className="bd-tree">{[...tree.entries()].map(([area,fronts])=><div className={`bd-tree-node ${openAreas.has(area)?'is-open':''}`} key={area}><button type="button" className="bd-tree-row level-area" onClick={()=>toggle(setOpenAreas,area)}><strong>{area}</strong><b>{[...fronts.values()].reduce((sum,map)=>sum+map.size,0)}</b></button><div className="bd-tree-children">{[...fronts.entries()].map(([front,equipments])=>{const frontKey=`${area}|${front}`;return <div className={`bd-tree-node bd-tree__front ${openFronts.has(frontKey)?'is-open':''}`} key={frontKey}><button type="button" className="bd-tree-row level-front" onClick={()=>toggle(setOpenFronts,frontKey)}><strong>{front}</strong><b>{equipments.size}</b></button><div className="bd-tree-children">{[...equipments.entries()].map(([code,equipmentRows])=>{const indicators=calculateIndicators(sumRows(equipmentRows));return <button type="button" key={code} className="bd-equipment-card" onClick={()=>onOpenEquipment({code,rows:equipmentRows})}><div className="bd-equipment-card__head"><strong>{code}</strong><span>{equipmentRows[0]?.desc_equip}</span></div><div className="bd-equipment-tags">{EQUIPMENT_TAGS.map((tag)=><span key={tag.key} className={`is-${kpiTone(tag.key,indicators[tag.key])}`}><b>{tag.short}</b>{formatPercent(indicators[tag.key],1)}</span>)}</div></button>;})}</div></div>;})}</div></div>)}</div>;}

function DistributionChart({totals}){const items=OPERATION_GROUPS.map((item)=>({...item,value:totals[item.key]||0})),max=Math.max(1,...items.map((item)=>item.value));return <div className="bd-distribution bd-distribution--dashboard">{items.map((item)=><div key={item.key}><span>{item.label}</span><div><i style={{width:`${(item.value/max)*100}%`,background:item.color}}/></div><strong>{formatDuration(item.value)}</strong></div>)}</div>;}
function Offenders({rows,totalOperational}){const offenders=useMemo(()=>{const map=new Map();rows.filter((row)=>['IMPRODUTIVO','AUXILIAR'].includes(String(row.desc_grupo_op||'').toUpperCase())).forEach((row)=>{const key=row.desc_operacao||'NÃO INFORMADA';map.set(key,(map.get(key)||0)+num(row.hrs_operacionais_seg));});return[...map.entries()].map(([name,seconds])=>({name,seconds})).sort((a,b)=>b.seconds-a.seconds).slice(0,10);},[rows]);const max=Math.max(1,...offenders.map((item)=>item.seconds));return <div className="bd-offenders"><div className="bd-offenders__head"><span>Operação</span><b>Tempo</b><b>%</b></div>{offenders.map((item,index)=><div className="bd-offender" key={item.name}><span>{String(index+1).padStart(2,'0')}</span><div><strong>{item.name}</strong><div><i style={{width:`${(item.seconds/max)*100}%`}}/></div></div><b>{formatDuration(item.seconds)}</b><b>{formatPercent(safePercent(item.seconds,totalOperational))}</b></div>)}</div>;}


class BoletimErrorBoundary extends React.Component {
  constructor(props){super(props);this.state={error:null};}
  static getDerivedStateFromError(error){return{error};}
  componentDidCatch(error,info){console.error('[COA] Boletim Diário:',error,info);}
  render(){if(this.state.error)return <div className="bd-state is-error"><strong>Não foi possível renderizar o Boletim Diário</strong><p>{this.state.error?.message||'Erro inesperado de renderização.'}</p></div>;return this.props.children;}
}

function BoletimDiarioContent(){
 const[dates,setDates]=useState([]),[selectedDate,setSelectedDate]=useState(''),[calendarOpen,setCalendarOpen]=useState(false),[activeCategories,setActiveCategories]=useState(DEFAULT_CATEGORIES),[selectedAreas,setSelectedAreas]=useState([]),[selectedFronts,setSelectedFronts]=useState([]),[equipmentSearch,setEquipmentSearch]=useState(''),[dayRows,setDayRows]=useState([]),[historyRows,setHistoryRows]=useState([]),[equipmentRows,setEquipmentRows]=useState([]),[operationRows,setOperationRows]=useState([]),[operationsLoading,setOperationsLoading]=useState(false),[selectedEquipment,setSelectedEquipment]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tooltip,setTooltip]=useState(null),[filterOpen,setFilterOpen]=useState(false);
 useEffect(()=>{let active=true;(async()=>{const{data,error:queryError}=await supabase.from('vw_c_boletimdiario_datas').select('*').order('data',{ascending:false});if(!active)return;if(queryError){setError(queryError.message);setLoading(false);return;}const source=Array.isArray(data)?data:[];setDates(source);setSelectedDate(source[0]?.data||'');})();return()=>{active=false;};},[]);
 useEffect(()=>{if(!selectedDate||!dates.length)return undefined;let active=true;(async()=>{setLoading(true);setOperationsLoading(true);setError('');setSelectedEquipment(null);const index=dates.findIndex((item)=>item.data===selectedDate),sevenDates=dates.slice(index,index+7).map((item)=>item.data).sort(),start=sevenDates[0]||selectedDate,end=sevenDates.at(-1)||selectedDate,cacheKey=`${selectedDate}|${start}|${end}`;try{let payload=DATA_CACHE.get(cacheKey);if(!payload){const[day,history,equipments]=await Promise.all([fetchAllPages(()=>supabase.from('vw_c_boletimdiario_dia').select('*').eq('data',selectedDate)),fetchAllPages(()=>supabase.from('vw_c_boletimdiario_dia_area').select('*').gte('data',start).lte('data',end)),fetchAllPages(()=>supabase.from('vw_c_boletimdiario_equipamento').select('*').eq('data',selectedDate))]);payload={day:normalizeRows(day),history:normalizeRows(history),equipments:normalizeRows(equipments)};DATA_CACHE.set(cacheKey,payload);}if(!active)return;setDayRows(payload.day);setHistoryRows(payload.history);setEquipmentRows(payload.equipments);setLoading(false);let operations=OPERATIONS_CACHE.get(selectedDate);if(!operations){operations=normalizeRows(await fetchAllPages(()=>supabase.from('vw_c_boletimdiario_equip_operacoes').select('*').eq('data',selectedDate)));OPERATIONS_CACHE.set(selectedDate,operations);}if(active)setOperationRows(operations);}catch(loadError){if(active)setError(loadError.message||'Erro ao carregar dados.');}finally{if(active){setLoading(false);setOperationsLoading(false);}}})();return()=>{active=false;};},[selectedDate,dates]);
 const categories=useMemo(()=>[...new Set([...dayRows,...historyRows].map((row)=>row.categoria).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[dayRows,historyRows]);
 const categoryDay=useMemo(()=>dayRows.filter((row)=>activeCategories.includes(row.categoria)),[dayRows,activeCategories]);
 const areaOptions=useMemo(()=>[...new Set(categoryDay.map((row)=>row.desc_area).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR')).map((name)=>({name,count:new Set(equipmentRows.filter((row)=>activeCategories.includes(row.categoria)&&row.desc_area===name).map((row)=>row.cod_equip)).size,fronts:[...new Set(categoryDay.filter((row)=>row.desc_area===name).map((row)=>row.desc_grupo))]})),[categoryDay,equipmentRows,activeCategories,selectedFronts]);
 const frontOptions=useMemo(()=>[...new Set(categoryDay.map((row)=>row.desc_grupo).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR')).map((name)=>({name,count:new Set(equipmentRows.filter((row)=>activeCategories.includes(row.categoria)&&row.desc_grupo===name).map((row)=>row.cod_equip)).size,areas:[...new Set(categoryDay.filter((row)=>row.desc_grupo===name).map((row)=>row.desc_area))]})),[categoryDay,equipmentRows,activeCategories,selectedAreas]);
 const matchesFilters=(row)=>activeCategories.includes(row.categoria)&&(!selectedAreas.length||selectedAreas.includes(row.desc_area))&&(!selectedFronts.length||selectedFronts.includes(row.desc_grupo));
 const filteredDay=useMemo(()=>dayRows.filter(matchesFilters),[dayRows,activeCategories,selectedAreas,selectedFronts]);
 const filteredEquipments=useMemo(()=>equipmentRows.filter(matchesFilters).filter((row)=>`${row.cod_equip} ${row.desc_equip}`.toLowerCase().includes(equipmentSearch.toLowerCase().trim())),[equipmentRows,activeCategories,selectedAreas,selectedFronts,equipmentSearch]);
 const filteredOperations=useMemo(()=>operationRows.filter(matchesFilters),[operationRows,activeCategories,selectedAreas,selectedFronts]);
 const totals=useMemo(()=>sumRows(filteredDay),[filteredDay]),indicators=useMemo(()=>calculateIndicators(totals),[totals]);
 const historyByKpi=useMemo(()=>{const result=Object.fromEntries(KPI_CONFIG.map(({key})=>[key,[]]));[...new Set(historyRows.map((row)=>row.data))].sort().forEach((date)=>{const rows=historyRows.filter((row)=>row.data===date&&activeCategories.includes(row.categoria)&&(!selectedAreas.length||selectedAreas.includes(row.desc_area)));const values=calculateIndicators(sumRows(rows));KPI_CONFIG.forEach(({key})=>result[key].push({data:date,value:values[key]}));});return result;},[historyRows,activeCategories,selectedAreas]);
 const offenderTotal=useMemo(()=>filteredOperations.filter((row)=>['IMPRODUTIVO','AUXILIAR'].includes(String(row.desc_grupo_op||'').toUpperCase())).reduce((sum,row)=>sum+num(row.hrs_operacionais_seg),0),[filteredOperations]);
 const toggleCategory=(category)=>setActiveCategories((previous)=>previous.includes(category)?previous.length===1?previous:previous.filter((item)=>item!==category):[...previous,category]);
 const toggleList=(setter,value)=>setter((previous)=>previous.includes(value)?previous.filter((item)=>item!==value):[...previous,value]);
 const openCalendarFromModal=()=>{setSelectedEquipment(null);setCalendarOpen(true);};
 const openTooltip=(event,config,history,currentValue)=>{const rect=event.currentTarget.getBoundingClientRect(),left=Math.min(window.innerWidth-DASH_CONFIG.tooltipWidth-12,Math.max(12,rect.left+rect.width/2-DASH_CONFIG.tooltipWidth/2));let top=rect.top-DASH_CONFIG.tooltipHeight-12;if(top<12)top=rect.bottom+12;setTooltip({config,history,currentValue,position:{left,top}});};
 if(loading&&!dayRows.length)return <div className="bd-state"><div className="coa-loader-dots"><span/><span/><span/></div><p>Carregando Boletim Diário…</p></div>;if(error)return <div className="bd-state is-error"><strong>Erro ao carregar</strong><p>{error}</p></div>;
 return <><div className="bd-dashboard"><FilterRail categories={categories} activeCategories={activeCategories} onToggleCategory={toggleCategory} selectedAreas={selectedAreas} selectedFronts={selectedFronts} onOpenFilter={()=>setFilterOpen(true)} search={equipmentSearch} onSearch={setEquipmentSearch}/><main className="bd-main"><section className="bd-context-bar"><div className="bd-context-title"><span className="bd-overline">Boletim Geral dos Equipamentos</span><div><h2>{formatDate(selectedDate)}</h2><button type="button" onClick={()=>setCalendarOpen(true)} title="Selecionar data">📆</button></div></div><div className="bd-equipment-count"><strong>{new Set(filteredEquipments.map((row)=>row.cod_equip)).size}</strong><span>equipamentos</span></div></section><section className="bd-kpi-grid">{KPI_CONFIG.map((config)=><KpiCard key={config.key} config={config} value={indicators[config.key]} history={historyByKpi[config.key]||[]} onTooltip={openTooltip} onTooltipClose={()=>setTooltip(null)}/>)}</section><section className="bd-workspace-grid"><article className="bd-panel bd-tree-panel"><header><div><span className="bd-overline">Navegação operacional</span><h3>Área · Frente · Equipamento</h3></div><span>{new Set(filteredEquipments.map((row)=>row.cod_equip)).size}</span></header><div className="bd-panel__scroll coa-no-scrollbar"><EquipmentTree rows={filteredEquipments} onOpenEquipment={setSelectedEquipment} search={equipmentSearch}/></div></article><article className="bd-panel"><header><div><span className="bd-overline">Distribuição</span><h3>Grupo de Operações</h3></div><span>{formatDuration(totals.hrs_operacionais_seg)}</span></header><div className="bd-panel__body"><DistributionChart totals={totals}/></div></article><article className="bd-panel"><header><div><span className="bd-overline">Top 10</span><h3>Ofensores operacionais</h3></div><span>{operationsLoading?'Carregando…':formatDuration(offenderTotal)}</span></header><div className="bd-panel__scroll coa-no-scrollbar"><Offenders rows={filteredOperations} totalOperational={totals.hrs_operacionais_seg}/></div></article></section></main>{loading&&<div className="bd-refreshing"><span/>Atualizando</div>}{filterOpen&&<FilterModal areaOptions={areaOptions} frontOptions={frontOptions} selectedAreas={selectedAreas} selectedFronts={selectedFronts} onApply={(areas,fronts)=>{setSelectedAreas(areas);setSelectedFronts(fronts);}} onClose={()=>setFilterOpen(false)}/>} {calendarOpen&&<CalendarModal dates={dates} selectedDate={selectedDate} onSelect={setSelectedDate} onClose={()=>setCalendarOpen(false)}/>} {selectedEquipment&&<BoletimDiarioModal equipment={selectedEquipment} operations={operationRows} selectedDate={selectedDate} onRequestDateChange={openCalendarFromModal} onClose={()=>setSelectedEquipment(null)}/>}</div><DashboardTooltip tooltip={tooltip}/></>;
}

export default function BoletimDiario(){return <BoletimErrorBoundary><BoletimDiarioContent/></BoletimErrorBoundary>;}
