name: Atualizar Dados COA

on:
  schedule:
    - cron: '15 14 * * *'
    - cron: '0 3,12,13,15,21 * * *' 
  workflow_dispatch: 

jobs:
  atualizar-base:
    runs-on: ubuntu-latest
    
    steps:
      - name: Puxar o código fonte
        uses: actions/checkout@v4 # Atualizado para v4 (Node 20+)

      - name: Preparar ambiente Python
        uses: actions/setup-python@v5 # Atualizado para v5 (Node 20+)
        with:
          python-version: '3.10'

      - name: Instalar biblioteca requests
        run: pip install requests

      - name: Executar o Extrator da Umeko
        run: python scripts/atualizar_dados.py

      - name: Commit e Push para a Vercel compilar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/mockData_coa.json
          git add src/data/coa_update.json
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: dados coa atualizados (auto)" && git push)