name: Atualizar Dados COA

on:
  schedule:
    # 14:15 UTC é exatamente 11:15 em Brasília (O seu teste)
    - cron: '15 14 * * *'
    # 12, 13, 15, 21, e 03 UTC correspondem a: 09h, 10h, 12h, 18h e 00h no Brasil
    - cron: '0 3,12,13,15,21 * * *' 
  workflow_dispatch: # Botão mágico pra você forçar a rodada lá no site do GitHub

jobs:
  atualizar-base:
    runs-on: ubuntu-latest
    
    steps:
      - name: Puxar o código fonte
        uses: actions/checkout@v3

      - name: Preparar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar biblioteca requests
        run: pip install requests

      - name: Executar o Extrator da Umeko
        run: python scripts/atualizar_dados.py

      - name: Commit e Push para a Vercel compilar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/mockData_coa.json
          git add src/data/coa_update.json
          
          # Se não houver alteração de ontem pra hoje, ele não faz commit atoa
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: dados coa atualizados (auto)" && git push)